language: node_js
node_js: '8'
cache: yarn
addons:
  code_climate:
    repo_token: 'your repo token'
  firefox: "51.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  email: false
before_script:
  - npm install codeclimate-test-reporter
  - alias codeclimate="./node_modules/codeclimate-test-reporter/bin/codeclimate.js"
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
